export const USE_CASE_REGISTRY = {
  ACCOUNT: {
    CREATE: Symbol('MODULE::APPLICATION::USE_CASE::ACCOUNT::CREATE'),
    DELETE: Symbol('MODULE::APPLICATION::USE_CASE::ACCOUNT::DELETE'),
    FIND: {
      CURRENT: Symbol('MODULE::APPLICATION::USE_CASE::ACCOUNT::FIND::CURRENT'),
    },
  },
};
