export const EXPRESS_HTTP_MIDDLEWARE_REGISTRY = {
  ERROR: Symbol('MODULE::APPLICATION::MIDDLEWARE::HTTP::EXPRESS::ERROR'),
  LOGGER: {
    REQUEST: Symbol(
      'MODULE::APPLICATION::MIDDLEWARE::HTTP::EXPRESS::LOGGER::REQUEST',
    ),
    ERROR: Symbol(
      'MODULE::APPLICATION::MIDDLEWARE::HTTP::EXPRESS::LOGGER::ERROR',
    ),
  },
};
